filter:
    paths: [ src/* ]
    excluded_paths: [ vendor/*, tests/* ]
before_commands:
    - 'composer install --dev --prefer-dist'
tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
nodes:
    analysis:
        project_setup:
            override:
                - 'true'
        tests:
            override:
                - php ./vendor/bin/simple-phpunit --configuration phpunit.xml.dist
